services:

  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      - PREFECT_HOME=/root/.prefect
    volumes:
      - prefect-data:/root/.prefect
    restart: unless-stopped

  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph
    command: ["--schema-info-enabled=True"]
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MGCONSOLE=--username memgraph --password memgraph
      - MEMGRAPH=--query-modules-on-startup=node_similarity
    volumes:
      - memgraph-data:/var/lib/memgraph
    stop_grace_period: 60s
    restart: unless-stopped

  memgraph_lab:
    image: memgraph/lab:latest
    container_name: memgraph_lab
    ports:
      - "3000:3000"
    environment:
      QUICK_CONNECT_MG_HOST: memgraph
    depends_on:
      - memgraph
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__LOGGING__LEVEL=INFO
    restart: unless-stopped

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  prefect-data:
  memgraph-data:
  qdrant_storage:
  valkey-data2:
  searxng-data:
